### ISSUE TITLE
Adding a section on installation instruction to README?

### ISSUE THREAD

**Issue by hongzhouye** [bjmorgan/py-sc-fermi#18]
Hi developers, what's your thought on adding a short section summarizing the installation command (`python setup.py install`) as well as all the prerequisites? Some people may be unfamiliar with the setup command; others may have a hard time gathering all prerequisites which are currently distributed in `setup.py` and `requirements.txt`.

I myself particularly had the following error
```
SyntaxError: future feature annotations is not defined
```
which occurred because I was using Python 3.6 and somehow the requirement `>=3.8` in `setup.py` didn't work for me. Explicitly pointing this and other requirements out in the `README` may be helpful to some users. My 2c.

**Comment by hongzhouye** [comment]
I closed it because I realized that the installation instruction is included in the separate document.

**Comment by alexsquires** [comment]
I think it cannot hurt to be clearer about this, and I will include the installation instructions in the README in addition to the docs.
