### ISSUE TITLE
Adding a few examples?

### ISSUE THREAD

**Issue by hongzhouye** [bjmorgan/py-sc-fermi#19]
Hi developers, what's your thought on adding some examples that demonstrate, *ideally in a step-by-step way with explanatory comments*, the use of the code in close-to-real-life situations? The unit tests you have currently in the `tests` folder are great but may be slightly less straightforward for new users who are exploring what functionalities the code can provide.

This will also help meet the following requirement from JOSS:
> **Example usage**: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Thanks!

**Comment by alexsquires** [comment]
Hi Hong-Zhou, 

Are the examples given at: https://py-sc-fermi.readthedocs.io/en/latest/tutorials.html enough?

If that is the case, and you just didn't see them, we clearly need to increase the visibility of the documentation in the GitHub repo!

**Comment by hongzhouye** [comment]
Yes, they are perfect thanks!
