### ISSUE TITLE
SC Fermi compatability

### ISSUE THREAD

**Issue by alexsquires** [bjmorgan/py-sc-fermi#2]
@bjmorgan, currently, py-sc-Fermi has the ability to read/write SC-Fermi io. Do we want to maintain this? It necessitates adding otherwise redundant properties to various objects. These properties could be confusing to a hypothetical user who is not familiar with the FORTRAN code.

**Comment by bjmorgan** [comment]
What are some examples of "redundant properties"?

**Comment by alexsquires** [comment]
on reflection, have decided to keep this in because it would mean refactoring the supporting analysis for Li3OCl.
