### ISSUE TITLE
defect_system.report()

### ISSUE THREAD

**Issue by ajgoyal** [bjmorgan/py-sc-fermi#24]
It will be useful to have temperature as output for defect_system.report()

**Comment by bjmorgan** [comment]
@alexsquires I remember the `defect_system.report()` was written to directly emulate the output of Fortran sc-Fermi code. And e.g. `defect_system.__repr__()` *does* report the temperature. I do not see a reason to not add the temperature to the `report()` method beyond maintaining historical consistency?

**Comment by alexsquires** [comment]
Yes, I am happy to do this

**Comment by ajgoyal** [comment]
Thanks!
