### ISSUE TITLE
Saving/loading from disk

### ISSUE THREAD

**Issue by zhubonan** [bjmorgan/py-sc-fermi#28]
I don't think there is any functionality for saving/loading data from the disk?

Would be useful to have such functionalities so `DefectSystem` can be saved (loaded) from (to) disk (object storages). 

Probably the easiest way is to use the `MSONable` [interface](https://pythonhosted.org/monty/monty.html#monty.json.MSONable)?
I think all base data types involved for creating `DefectSystem` are JSON serializable.

**Comment by alexsquires** [comment]
Check out the jsonable branch! On there each object has `as_dict()` and `from_dict()` methods to enable this. 

It's not merged yet because it needs to be reconciled with the CLI, but I don't think you'll need to use that. In fact, it would be nice if you could use it and flag any issues.

**Comment by zhubonan** [comment]
Great, glad to know it has been taken care of!
