### ISSUE TITLE
RuntimeWarning: overflow encountered in exp   + np.exp(

### ISSUE THREAD

**Issue by chentingxi36** [bjmorgan/py-sc-fermi#29]
I find this question in your API tutorial :"/Users/alex/work/py-sc-fermi/py_sc_fermi/dos.py:231: RuntimeWarning: overflow encountered in exp  + np.exp(" , and I don't kown whether this warming will influence the result

**Comment by alexsquires** [comment]
Hi @chentingxi36

This occurs when numpy encounters very very large numbers. This can generally be ignored as long as your results look reasonable. It is usually a consequence of 

1. The solver trialling a Fermi energy that causes unrealistic defect concentrations (you can ignore this so long as your defect concentrations at the final Fermi energy look reasonable)
2. Your input temperature is too high, and you are getting unphysically high defect concentrations (I have not encountered this at any meaningful temperature I have wished to simulate) 

Please let me know if you have further questions, or else I will close this issue in the next couple of days. 

Thanks for your interest in the code!

**Comment by bjmorgan** [comment]
@alexsquires The smart thing for us to do here is to catch this warning and add an additional "warning" that briefly covers your answer above.

**Comment by chentingxi36** [comment]
May I know your email address? I am trying to use your code, but I am not sure if the results I obtained are correct. I would like you to help me take a look。Think you!

**Comment by alexsquires** [comment]
> May I know your email address? I am trying to use your code, but I am not sure if the results I obtained are correct. I would like you to help me take a look。Think you!

My email address is available on my GitHub profile
