### ISSUE TITLE
read nelect in DOS.from_vasprun

### ISSUE THREAD

**Issue by alexsquires** [bjmorgan/py-sc-fermi#32]
as title, user would no longer have to specify nelect when reading a dos from a vasprun.

**Comment by bjmorgan** [comment]
I suspect this is a “how SC-Fermi does it” issue.

**Comment by alexsquires** [comment]
No, it's a me thing. For a long time I didn't think you could get at nelect from the `pymatgen.io.vasp.Vasprun` object, but you can: `pymatgen.io.vasp.Vasprun.parameters["NELECT"]
