### ISSUE TITLE
Quenched Fermi level

### ISSUE THREAD

**Issue by yuan-gist** [bjmorgan/py-sc-fermi#35]
Not sure someone have the same puzzle as below:

From my knowledge of literature, the quenched Fermi level is closer to the band edge. Is it possible that the quenched Fermi level becomes deeper in the band gap? Or could there be two solutions of the quenched Fermi?

**Comment by alexsquires** [comment]
Hi,

Could you clarify what you mean by the quenched Fermi energy? If you are describing what I think you are, I would generally expect lowering the temperature to bring the Fermi energy deeper into the gap.

**Comment by yuan-gist** [comment]
Thanks! By quenched Fermi level, I mean a rapid quenching from a high temperature (like 1000 K) to a low temperature (like 300 K) with fixing the defect concentration at the high temperature, and computing the Fermi level at the low temperature. The defect concentration can re-distribute between different charge states in quenching.

Like FIG. 10 of "https://journals.aps.org/prb/pdf/10.1103/PhysRevB.90.125202" and FIG. 4 of "https://journals.aps.org/prb/pdf/10.1103/PhysRevB.90.245202", the quenched Fermi level moves closer to the band edge.

**Comment by alexsquires** [comment]
I see. Are you trying to compare results you have obtained using `py-sc-fermi` to these literature results? When I am struggling to understand my compensation behaviour, I often find it instrurctive to plot my concentrations as a function of the Fermi energy e.g. 

https://py-sc-fermi.readthedocs.io/en/latest/tutorial.html#plot-defect-concentrations-as-a-function-of-Fermi-energy

And then you can observe which charged species are contributing to whatever you perceive to be unexpected behaviour. Without more detail it would be difficult to diagnose what might be happening in your system.

**Comment by bjmorgan** [comment]
I could imagine this is system-dependent, as the response will be affected by the set of defects and charge states in your model, their formation energies, and possibly also the densities of states at the edges of the conduction and valence bands.

**Comment by yuan-gist** [comment]
I see. Thanks a lot!
