### ISSUE TITLE
'DefectSystem' object has no attribute 'concentration_dict'

### ISSUE THREAD

**Issue by msehabibur** [bjmorgan/py-sc-fermi#36]
When I try to plot the concentration as a function of T, it shows the 'DefectSystem' object has no attribute 'concentration_dict'. 
<img width="535" alt="Screenshot 2024-03-22 at 10 18 47 AM" src="https://github.com/bjmorgan/py-sc-fermi/assets/96934016/504d1c7c-9625-45e9-9c8d-4fabace77762">

**Comment by bjmorgan** [comment]
@msehabibur It's not possible to see what the issue is from your code snippet. Can you post a fuller example that includes any previous references to the variable `defect_system`?

`concentration_dict` is a method, not an attribute, but the code above shouldn't give an `AtttibuteError` if `defect_system` is a `DefectSystem` object.

**Comment by msehabibur** [comment]
<img width="730" alt="Screenshot 2024-03-22 at 10 45 10 AM" src="https://github.com/bjmorgan/py-sc-fermi/assets/96934016/b45a8393-799f-4995-b9e8-87ce18000909">

**Comment by bjmorgan** [comment]
@msehabibur how do you create and then reference the `defect_system` variable?

**Comment by msehabibur** [comment]
<img width="1001" alt="Screenshot 2024-03-22 at 11 04 43 AM" src="https://github.com/bjmorgan/py-sc-fermi/assets/96934016/f48b86f4-6a21-4afe-9167-8d852911a0df">

**Comment by alexsquires** [comment]
Could you confirm the version of `py_sc_fermi` you are using? For versions earlier than 2.0.0 the `concentration_dict()` method functionality is found under `DefectSystem.as_dict()`

**Comment by msehabibur** [comment]
I just updated the version, and the problem is solved! Thank you!

**Comment by msehabibur** [comment]
Completed
