### ISSUE TITLE
SC-Fermi Issue

### ISSUE THREAD

**Issue by msehabibur** [bjmorgan/py-sc-fermi#37]
In my attempts to calculate the sc-Fermi level, it appears there's an issue with how the code interprets this level. Upon reviewing the provided plot, it's noticeable that, contrary to expectations, the sc-Fermi level is positioned closer to the conduction band minimum (CBM) rather than being near the valence band maximum (VBM), where it ideally should be. This discrepancy is particularly concerning given that the calculation should account for carrier concentration, but the magnitude of the offset observed seems to extend beyond reasonable limits. 
<img width="385" alt="Screenshot 2024-03-27 at 3 18 54 PM" src="https://github.com/bjmorgan/py-sc-fermi/assets/96934016/ced7f6d0-90ee-45b5-93e0-1b52f771ad64">

**Comment by alexsquires** [comment]
It's impossible to diagnose what might be going on here without more information, do you have a MWE to reproduce this behaviour?

**Comment by msehabibur** [comment]
<img width="828" alt="Screenshot 2024-03-28 at 11 19 13 AM" src="https://github.com/bjmorgan/py-sc-fermi/assets/96934016/5d3cf657-dbd6-4274-80e2-a2a964b9f519">
<img width="675" alt="Screenshot 2024-03-28 at 11 19 30 AM" src="https://github.com/bjmorgan/py-sc-fermi/assets/96934016/3dfca3a4-c4f9-4a59-b662-318a8bb50ab5">

**Comment by alexsquires** [comment]
From a set of screenshots with no access to the DOS, it is still effectively impossible for me to suggest what the issue might be. Can you either provide a minimal working example, or if you don't want to do this, I would recommend plotting [concentrations as a function of Fermi energy](https://py-sc-fermi.readthedocs.io/en/latest/tutorial.html#plot-defect-concentrations-as-a-function-of-Fermi-energy) - I tend to find that plotting this usually clears up what the reason for non-intuitive compensation behaviour might be.

**Comment by alexsquires** [comment]
Going to close this due to inactivity, please reopen if you have further queries @msehabibur
