### ISSUE TITLE
Changing temperature of defect system gives unexpected results

### ISSUE THREAD

**Issue by utf** [bjmorgan/py-sc-fermi#7]
We are using py-sc-fermi to model defect concentrations of quenched systems. This involves i) calculating defect concentrations at high temperature, ii) fixing the concentrations to these values, and  iii)  calculating the SC Fermi level at room temperature using the fixed concentrations. To achieve this, we used the following code:

```python
# initial temp of 1400 K
defect_system = DefectSystem(defects, dos, volume, 1400)
defects = defect_system.to_dict()

# fix defect concs
fixed_defects = [k for k in defects.keys() if k not in ['Fermi Energy', 'n0', 'p0']]
for defect_label in fixed_defects:
    defect_system.defect_species_by_name(defect_label).fix_concentration(defects[defect_label])

# switch to 300 K and calculate Fermi level
defect_system.temperature = 300
defect_system.report()
```

However, this gave unexpected results in the defect concentrations and Fermi level. Namely, despite the Fermi level being in the middle of a wide band gap semiconductor, the n and p-type carrier concentrations were very large.

We realised this is because k_B * T is cached in the `DefectSystem` object as the `.kT` attribute and must also be set when changing the temperature. I.e., changing the code to the following fixed the issue:

```python
from py_sc_fermi.constants import kboltz

# switch to 300 K and calculate Fermi level
defect_system.kT = 300 * kboltz
defect_system.temperature = 300
defect_system.report()
```

It might make things easier if `kT` is not cached. You could also add an example of this usage of py-sc-fermi in the jupyter notebook.

**Comment by bjmorgan** [comment]
I agree with your proposal @utf. The code is cleaner if we just calculate kT where we need it, and then we are guaranteed to avoid unexpected behaviour if people change T during a calculation.
