### ISSUE TITLE
Request for developer's help on degradation factors

### ISSUE THREAD

**Issue by iamcqlin** [bjmorgan/py-sc-fermi#9]
Hello Dear Developer.

Thank you for reading!

Py-sc-fermi is a very commendable software that allows us to calculate some properties of crystal defects very easily. However, I have encountered some confusion as a novice.

I found that I need to enter the degeneracy factor of the defect level when calculating the defect concentration. I would like to know how this parameter is calculated.

I am wondering if you could kindly share with me the necessary information about it. If it's too much trouble, could you send me some relevant information?

Thank you very much for your kind consideration and I am looking forward to your early reply.

Best regards!
Changqing Lin

28/4/2022

**Comment by alexsquires** [comment]
If you are asking about the degeneracy of `DefectSpecies` (`nsites`) that is simply the number of energetically equivalent sites on which the defect can form. 

The degeneracy of a `DefectChargeState` is more complicated, but is conceptually similar, in that it is the number of energetically degenerate configurations of the charge state.

If we consider the following case, where we have a trigonally coordinated cation somewhere in our structure. If that cation forms a **neutral** vacancy, let's assume that the hole associated with that defect is localised, it might localise on any one of the three coordinating anions, and it might be spin up, or spin down. So the degeneracy of this `DefectChargeState` will be six. 

![image](https://user-images.githubusercontent.com/22589426/165715700-7fc8d02d-9f86-4a92-bf96-6ad797ec556f.png)

If, however, the hole is delocalised, you have a degeneracy of 2, as the delocalised density is spin up, or spin down.

**Comment by iamcqlin** [comment]
Hello Dear Alex Squires. 

Thank you for your answer, which solved my confusion.

Thank you very much for your kind consideration

Best regards!
Changqing Lin

02/05/2022
